/*
 * Grocery List Management API
 *
 * A simple REST API for managing a grocery shopping list, designed for student term projects.
 *
 * API version: 1.0.0
 * Contact: support@example.edu
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"time"
)

type GroceryItem struct {

	// Name of the grocery item
	Name string `json:"name"`

	// Quantity of the item needed
	Quantity int32 `json:"quantity"`

	// Unit of measurement
	Unit string `json:"unit,omitempty"`

	// Category of the item
	Category string `json:"category,omitempty"`

	// Additional notes about the item
	Notes string `json:"notes,omitempty"`

	// Unique identifier for the item
	Id int64 `json:"id"`

	// When the item was created
	CreatedAt time.Time `json:"createdAt"`

	// When the item was last updated
	UpdatedAt time.Time `json:"updatedAt"`

	// Whether the item has been purchased
	Purchased bool `json:"purchased,omitempty"`
}
