/*
 * Grocery List Management API
 *
 * A simple REST API for managing a grocery shopping list, designed for student term projects.
 *
 * API version: 1.0.0
 * Contact: support@example.edu
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// This file only contains comments documenting the struct fields
// The actual GroceryItem struct is defined in database.go

/*
GroceryItem struct fields:

Name: Name of the grocery item
Quantity: Quantity of the item needed
Unit: Unit of measurement
Category: Category of the item
Notes: Additional notes about the item
ID: Unique identifier for the item
CreatedAt: When the item was created
UpdatedAt: When the item was last updated
Purchased: Whether the item has been purchased
*/
