/*
 * Grocery List Management API
 *
 * A simple REST API for managing a grocery shopping list, designed for student term projects.
 *
 * API version: 1.0.0
 * Contact: support@example.edu
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type GroceryItemCreate struct {

	// Name of the grocery item
	Name string `json:"name"`

	// Quantity of the item needed
	Quantity int32 `json:"quantity"`

	// Unit of measurement
	Unit string `json:"unit,omitempty"`

	// Category of the item
	Category string `json:"category,omitempty"`

	// Additional notes about the item
	Notes string `json:"notes,omitempty"`
}
